In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import os

print("Carpeta actual:")
print(os.getcwd())

Carpeta actual:
/workspaces/Anime-final-project

In [3]:
import os

print(os.listdir())

['readme.md', 'package.json', '.gitignore', '.prettierrc', '.github', 'node_modules', 'package-lock.json', 'data', 'openapi-ts.config.ts', 'openapi.json', 'bun.lockb', 'src', '.git', 'state.json', 'tsconfig.json']

In [4]:
for item in os.listdir():
    print(item)

readme.md
package.json
.gitignore
.prettierrc
.github
node_modules
package-lock.json
data
openapi-ts.config.ts
openapi.json
bun.lockb
src
.git
state.json
tsconfig.json

In [5]:
import os

print(os.path.exists("data"))
print(os.path.exists("data/anime"))
print(os.path.exists("data/anime/anime-standalone.csv"))

True
True
False

In [6]:
df = pd.read_csv("data/anime-standalone.csv")
df.head()

,id,title,titleJa,titleEn,image,mean,rank,num_list_users,num_scoring_users,num_episodes,start_date,end_date,media_type,status,rating,average_episode_duration,genres,studios
0,1,Cowboy Bebop,カウボーイビバップ,Cowboy Bebop,https://myanimelist.net/images/anime/4/19644.jpg,8.75,49.0,2051529,1059425,26,1998-04-03,1999-04-24,tv,finished_airing,r,1440,"Action, Adult Cast, Award Winning, Sci-Fi, Space",Sunrise
1,5,Cowboy Bebop: Tengoku no Tobira,カウボーイビバップ 天国の扉,Cowboy Bebop: The Movie,https://myanimelist.net/images/anime/1439/9348...,8.38,240.0,411130,231859,1,2001-09-01,2001-09-01,movie,finished_airing,r,6911,"Action, Adult Cast, Sci-Fi, Space",Bones
2,6,Trigun,トライガン,Trigun,https://myanimelist.net/images/anime/1130/1200...,8.22,419.0,832704,400891,26,1998-04-01,1998-09-30,tv,finished_airing,pg_13,1480,"Action, Adult Cast, Adventure, Sci-Fi, Shounen",Madhouse
3,7,Witch Hunter Robin,Witch Hunter ROBIN (ウイッチハンターロビン),Witch Hunter Robin,https://myanimelist.net/images/anime/10/19969.jpg,7.25,3527.0,129287,46530,26,2002-07-03,2002-12-25,tv,finished_airing,pg_13,1500,"Action, Detective, Drama, Mystery, Supernatural",Sunrise
4,8,Bouken Ou Beet,冒険王ビィト,Beet the Vandel Buster,https://myanimelist.net/images/anime/7/21569.webp,7.01,4893.0,16881,7226,52,2004-09-30,2005-09-29,tv,finished_airing,pg,1380,"Action, Adventure, Fantasy, Shounen",Toei Animation

In [8]:
df.shape

(24923, 18)

In [9]:
df.columns.tolist()

['id',
 'title',
 'titleJa',
 'titleEn',
 'image',
 'mean',
 'rank',
 'num_list_users',
 'num_scoring_users',
 'num_episodes',
 'start_date',
 'end_date',
 'media_type',
 'status',
 'rating',
 'average_episode_duration',
 'genres',
 'studios']

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 24923 entries, 0 to 24922
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id                        24923 non-null  int64
 1   title                     24923 non-null  str
 2   titleJa                   24827 non-null  str
 3   titleEn                   11964 non-null  str
 4   image                     24817 non-null  str
 5   mean                      18938 non-null  float64
 6   rank                      18157 non-null  float64
 7   num_list_users            24923 non-null  int64
 8   num_scoring_users         24923 non-null  int64
 9   num_episodes              24923 non-null  int64
 10  start_date                24923 non-null  str
 11  end_date                  24298 non-null  str
 12  media_type                24923 non-null  str
 13  status                    24923 non-null  str
 14  rating                    24639 non-null  str
 15  average_episode_duration  24923 non-null  int64
 16  genres                    24855 non-null  str
 17  studios                   17030 non-null  str
dtypes: float64(2), int64(5), str(11)
memory usage: 3.4 MB

In [11]:
df.describe(include="all")

,id,title,titleJa,titleEn,image,mean,rank,num_list_users,num_scoring_users,num_episodes,start_date,end_date,media_type,status,rating,average_episode_duration,genres,studios
count,24923.000000,24923,24827,11964,24817,18938.000000,18157.000000,2.492300e+04,2.492300e+04,24923.000000,24923,24298,24923,24923,24639,24923.000000,24855,17030
unique,NaN,24918,23855,11811,24817,NaN,NaN,NaN,NaN,NaN,9653,9599,10,3,6,NaN,5346,1961
top,NaN,Geomjeong Gomusin,おしりたんてい,Way of Choices,https://myanimelist.net/images/anime/4/19644.jpg,NaN,NaN,NaN,NaN,NaN,2026-07,2023-03-24,tv,finished_airing,pg_13,NaN,Music,Toei Animation
freq,NaN,2,10,6,1,NaN,NaN,NaN,NaN,NaN,51,23,6487,24405,10565,NaN,1961,846
mean,33142.585283,NaN,NaN,NaN,NaN,6.480900,9710.065374,4.681139e+04,2.369004e+04,11.160173,NaN,NaN,NaN,NaN,NaN,1335.280303,NaN,NaN
std,20700.031545,NaN,NaN,NaN,NaN,0.861085,6135.467997,1.849981e+05,1.100954e+05,44.244001,NaN,NaN,NaN,NaN,NaN,1529.406797,NaN,NaN
min,1.000000,NaN,NaN,NaN,NaN,1.890000,1.000000,2.100000e+01,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN
25%,10935.500000,NaN,NaN,NaN,NaN,5.870000,4544.000000,4.050000e+02,1.160000e+02,1.000000,NaN,NaN,NaN,NaN,NaN,229.000000,NaN,NaN
50%,36575.000000,NaN,NaN,NaN,NaN,6.460000,9120.000000,2.004000e+03,6.340000e+02,1.000000,NaN,NaN,NaN,NaN,NaN,1099.000000,NaN,NaN
75%,52403.500000,NaN,NaN,NaN,NaN,7.100000,14115.000000,1.409650e+04,5.266500e+03,12.000000,NaN,NaN,NaN,NaN,NaN,1500.000000,NaN,NaN
max,63986.000000,NaN,NaN,NaN,NaN,9.270000,22547.000000,4.347627e+06,3.059517e+06,3057.000000,NaN,NaN,NaN,NaN,NaN,10081.000000,NaN,NaN

In [12]:
df.isnull().sum().sort_values(ascending=False).head(20)

titleEn                     12959
studios                      7893
rank                         6766
mean                         5985
end_date                      625
rating                        284
image                         106
titleJa                        96
genres                         68
id                              0
title                           0
num_episodes                    0
num_list_users                  0
num_scoring_users               0
status                          0
media_type                      0
start_date                      0
average_episode_duration        0
dtype: int64

In [13]:
df = df.rename(columns={"mean": "score"})

In [14]:
df = df.dropna(subset=["score"])

In [15]:
selected_columns = [
    "title",
    "media_type",
    "num_episodes",
    "score",
    "num_scoring_users",
    "num_list_users",
    "rank",
    "popularity" if "popularity" in df.columns else None,
    "genres",
    "studios",
    "start_date"
]

selected_columns = [col for col in selected_columns if col is not None]

df = df[selected_columns].copy()

In [16]:
df.shape

(18938, 10)